matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_script:
        - npm install
      cache:
        directories:
          - "node_modules"
      script:
        - npm test

    - language: ruby
      ruby: 2.5.3
      gemfile:
        - Gemfile
      before_script:
        - bundle install
      script:
        - rspec --pattern **/spec/*_spec.rb
